-- =========================================================
-- SEATLOCK: Schema
-- PostgreSQL. Run this first, before any seed data.
-- =========================================================

CREATE TABLE app_user (
    user_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR NOT NULL,
    email       VARCHAR NOT NULL UNIQUE,
    created_at  TIMESTAMP DEFAULT now()
);
-- Named app_user rather than "user" -- "user" is a reserved word in PostgreSQL
-- and requires constant quoting; avoiding that headache from the start.

CREATE TABLE event (
    event_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR NOT NULL,
    event_date  DATE NOT NULL,
    venue       VARCHAR,
    created_at  TIMESTAMP DEFAULT now()
);

CREATE TABLE session (
    session_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      INT NOT NULL REFERENCES event(event_id),
    session_name  VARCHAR NOT NULL,
    start_time    TIMESTAMP NOT NULL,
    capacity      INT NOT NULL CHECK (capacity > 0),
    created_at    TIMESTAMP DEFAULT now()
);

CREATE TABLE seat (
    seat_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  INT NOT NULL REFERENCES session(session_id),
    seat_label  VARCHAR NOT NULL,
    UNIQUE (session_id, seat_label)   -- no duplicate seat labels within the same session
);

CREATE TABLE booking (
    booking_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat_id       INT NOT NULL REFERENCES seat(seat_id),
    user_id       INT NOT NULL REFERENCES app_user(user_id),
    status        VARCHAR NOT NULL DEFAULT 'Confirmed' CHECK (status IN ('Confirmed', 'Cancelled')),
    booked_at     TIMESTAMP DEFAULT now(),
    cancelled_at  TIMESTAMP
);

-- ---------------------------------------------------------
-- THE CORE CONCURRENCY GUARANTEE:
-- A seat can only have ONE active (Confirmed) booking at a time.
-- This partial unique index enforces that at the database level --
-- even if application logic has a race condition, Postgres itself
-- will reject a second confirmed booking for the same seat.
-- Cancelling a booking (status -> 'Cancelled') frees the seat,
-- since the index only applies to rows where status = 'Confirmed'.
-- ---------------------------------------------------------
CREATE UNIQUE INDEX idx_one_confirmed_booking_per_seat
ON booking (seat_id)
WHERE status = 'Confirmed';
